[package]
name = "rocket-auth-fractal"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "7.2.0"
jwks-client = { git = "https://github.com/jfbilodeau/jwks-client" }
reqwest = "0.11.7"
rocket = { version = "0.5.0-rc.1", features = ["uuid"] }
thiserror = "1.0.30"
tokio = "1.15.0"
